### ISSUE TITLE
Using twin_surrogates

### ISSUE THREAD

**Issue by manmeet3591** [pik-copan/pyunicorn#111]
Dear Sir

I am trying to test the twin_surrogates function using the test dataset ts and am getting the following error

Traceback (most recent call last):
  File "gen_twin_surrogate.py", line 34, in <module>
    surrogates = Surrogates.SmallTestData().twin_surrogates(ts, 10, 1, 0.5, 7)
  File "/iitm2/cccr-res/msingh/anaconda3/envs/python_2_7/lib/python2.7/site-packages/pyunicorn/timeseries/surrogates.py", line 625, in twin_surrogates
    twins = self.twins(embedding, threshold, min_dist)
  File "/iitm2/cccr-res/msingh/anaconda3/envs/python_2_7/lib/python2.7/site-packages/pyunicorn/timeseries/surrogates.py", line 359, in twins
    weave.inline(code, arg_names=args, type_converters=weave.converters.blitz, compiler='gcc',extra_compile_args=['-O3'])
  File "/iitm2/cccr-res/msingh/anaconda3/envs/python_2_7/lib/python2.7/site-packages/weave/inline_tools.py", line 366, in inline
    **kw)
  File "/iitm2/cccr-res/msingh/anaconda3/envs/python_2_7/lib/python2.7/site-packages/weave/inline_tools.py", line 473, in compile_function
    type_converters=type_converters)
  File "/iitm2/cccr-res/msingh/anaconda3/envs/python_2_7/lib/python2.7/site-packages/weave/ext_tools.py", line 182, in __init__
    auto_downcast, type_converters)
  File "/iitm2/cccr-res/msingh/anaconda3/envs/python_2_7/lib/python2.7/site-packages/weave/ext_tools.py", line 432, in assign_variable_types
    raise TypeError(format_error_msg(errors))
TypeError: {'dimension': "The type and dimensionality specificationsfor variable 'dimension' are missing."}

I am unable to undestand the error as to why its coming 
The statement throwing up this is 

surrogates = Surrogates.SmallTestData().twin_surrogates(ts, 10, 1, 0.5, 7)

where ts is the test data set obtained by 

ts = Surrogates.SmallTestData().original_data

**Comment by jdonges** [comment]
Dear Manmeet,

please try to use the latest version of pyunicorn (dev version on github) where this should be fixed. Note that the current dev version, which is to be released soon, runs only on Python 3.x.

Best regards,
Jonathan

**Comment by manmeet3591** [comment]
Thanks Jonathan. I'll try using the dev version. Please help me with the installation if possible, I guess I tried the github version installation previously.

Warm Regards
Manmeet

**Comment by manmeet3591** [comment]
Hi Jonathan 

I tried installing and using the dev version on github, but there is a lot of python 2.7 code in it due to which it doesnt work with python 3.5, like you can see below error

>>> import pyunicorn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/iitm2/cccr-res/msingh/Libraries/sources/pyunicorn/build/lib.linux-x86_64-3.5/pyunicorn/__init__.py", line 34, in <module>
    from .utils import mpi
  File "/iitm2/cccr-res/msingh/Libraries/sources/pyunicorn/build/lib.linux-x86_64-3.5/pyunicorn/utils/mpi.py", line 249
    print "MPI master : assigning call with id", id, "to slave", \
                                              ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by jdonges** [comment]
Hi,

we need to merge some pull requests fixing this. Please stay tuned for the next release of pyunicorn in a few weeks. This will be fully Python 3 compatible. Please excuse the inconvenience right now.

Best,
Jonathan
