### ISSUE TITLE
No module named 'setup' (v0.6.1)

### ISSUE THREAD

**Issue by Jsvcycling** [pik-copan/pyunicorn#129]
When attempting to import `pyunicorn` in Python 3.6.8 I receive the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jsvcycling/.local/lib/python3.6/site-packages/pyunicorn/__init__.py", line 43, in <module>
    from setup import __version__
ModuleNotFoundError: No module named 'setup'
```
I'm running on Ubuntu 18.04 LTS and installed pyunicorn (0.6.1) via pip. This problem does not occur in 0.6.0.post1.

My assumption is that the line in question is referring to `__version__` from the `setup.py` file but that file doesn't exist in the site-packages package.

**Comment by jkroenke** [comment]
Yes that file is indeed missing in the site-packages/pyunicorn folder. However, I deleted that line in pyunicorn/__init__.py and ran the tests without any problems occuring so that might be a quick workaround. The only disadvantage is that you cannot get the version number in the common way by typing 'pyunicorn.__version__'
