### ISSUE TITLE
error: no commands supplied

### ISSUE THREAD

**Issue by marlon-shiftone** [pik-copan/pyunicorn#143]
Traceback (most recent call last):
   
  File "/usr/local/lib/python3.6/dist-packages/spyder_kernels/customize/spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python3.6/dist-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/marlon/Shift One/Projeto Engie/projeto_engie/testes.py", line 13, in <module>
    import pyunicorn as pu

  File "/usr/local/lib/python3.6/dist-packages/pyunicorn/__init__.py", line 43, in <module>
    from setup import __version__

  File "/usr/local/lib/python3.6/dist-packages/setup.py", line 27, in <module>
    'Topic :: Utilities',

  File "/usr/lib/python3.6/distutils/core.py", line 136, in setup
    raise SystemExit(gen_usage(dist.script_name) + "\nerror: %s" % msg)

SystemExit: usage: testes.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: testes.py --help [cmd1 cmd2 ...]
   or: testes.py --help-commands
   or: testes.py cmd --help

error: no commands supplied

**Comment by ntfrgl** [comment]
Thank you for reporting this issue, and please accept our apologies for our delay in providing a rigorous solution. This set of problems should be fully resolved with the commit linked above, which will be reflected in an upcoming new release including official wheels. I'm tentatively closing this ticket, but please let us know in case you have any trouble installing `pyunicorn` from the current `master` branch, in which case we will attempt to find a solution as quickly as possible.

Cython is now declared as a build dependency, which means that your Python package manager (e.g., `pip`) is responsible for automatically providing the Cython compiler without any user intervention. After the package installation process is completed, Cython is **not** required as a runtime dependency. The version information is now retrieved via `importlib.metadata` from the Python standard library.
