### ISSUE TITLE
An AttributeError: can't set attribute error occurs when the RecurrencePlot method is referenced

### ISSUE THREAD

**Issue by Feaonan** [pik-copan/pyunicorn#176]
Traceback (most recent call last):
  File "D:\Software\Python3.7\lib\site-packages\pandas\core\generic.py", line 5518, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/pyunicorn/text.py", line 104, in <module>
    normalize=False, recurrence_rate=RR)
  File "D:\Software\Python3.7\lib\site-packages\pyunicorn\timeseries\recurrence_plot.py", line 149, in __init__
    self.time_series.shape = (self.time_series.shape[0], -1)
  File "D:\Software\Python3.7\lib\site-packages\pandas\core\generic.py", line 5528, in __setattr__
    object.__setattr__(self, name, value)
AttributeError: can't set attribute
Can anyone who knows what the problem is point out

**Comment by zugnachpankow** [comment]
Hey @Feaonan, 

thank you for reaching out to us. Since pandas seems to be raising an error, but pyunicorn does not use pandas, could you tell me if your input time series is a pandas series or data frame? If yes, please try to cast the pandas object into a numpy array, e.g. with `pandas.to_numpy()` method. 

If not, could you please tell me whats the shape of your time series and also provide a minimum example of code that reproduces your error, so i can look into it.

Thank you!

**Comment by Feaonan** [comment]
Problem solved thank you very much
