### ISSUE TITLE
numpy module not found during installation (Win10)

### ISSUE THREAD

**Issue by cherouny** [pik-copan/pyunicorn#212]
So for the last 3 hours I've been digging and not really successful as to how to install pyunicorn. I've installed all the required modules, installed a recent version of Visual C++, made sure to have the directories added to path in windows environment variables, tried to reinstall first just numpy, later python as a whole, treid an older python release, tried an older release of numpy etc etc. But I just can't figure out why I still end up with this error, in which ever way I try. But then again I'm quite the newbie

Any help is greatly appreciated.

I am currently running python 3.12 (also tried 3.7) and use VScode as an IDE, calling pip in an powershell terminal. Here are the packages I've got installed and below the error message I get from pip.

Package         Version
--------------- -------
contourpy       1.2.0
cycler          0.12.1
fonttools       4.47.0
h5netcdf        1.3.0
h5py            3.10.0
igraph          0.11.3
kiwisolver      1.4.5
numpy           1.26.2
packaging       23.2
Pillow          10.1.0
pip             23.3.2
pyparsing       3.1.1
python-dateutil 2.8.2
python-igraph   0.11.3
scipy           1.11.4
setuptools      69.0.2
six             1.16.0
texttable       1.7.0

PS C:\Users\Rouny> pip install pyunicorn
Collecting pyunicorn
  Using cached pyunicorn-0.6.1.tar.gz (881 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Rouny\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Rouny\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Rouny\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Rouny\AppData\Local\Temp\pip-build-env-y1xkl9f4\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Rouny\AppData\Local\Temp\pip-build-env-y1xkl9f4\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Rouny\AppData\Local\Temp\pip-build-env-y1xkl9f4\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Rouny\AppData\Local\Temp\pip-build-env-y1xkl9f4\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 21, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ntfrgl** [comment]
Because you tried installing from the [Python Package Index](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-from-pypi), you ended up with the latest official release `v0.6.1` (June 2019), which has a number of **known and solved** [installation problems](https://github.com/pik-copan/pyunicorn/issues?q=label%3Ainstallation+) due to its outdated package definition. While we are planning a new official release early next year, if you would like to use the package now, I strongly recommend installing the **current development version** from the `master` branch, see [our instructions](https://github.com/pik-copan/pyunicorn#current-development-version).

Please open a new issue if you find any installation problems with the development version.
